name: Launch EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  launch-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::533267177980:role/OIDC_Role
          aws-region: ap-south-1

      - name: Launch EC2 instance
        run: |
          aws ec2 run-instances \
            --image-id ami-0ad21ae1d0696ad58 \ # Example AMI ID, replace with your preferred AMI
            --count 1 \
            --instance-type t2.micro \
            --key-name MumbaiKey \
            # --security-group-ids YOUR_SECURITY_GROUP_ID \
            # --subnet-id YOUR_SUBNET_ID

      - name: Print environment variables
        run: env
